std_msgs/Header header

uint8 motor1_online
int16 motor1_current
int16 motor1_speed
uint16 motor1_encoder
uint8 motor1_temperature

uint8 motor2_online
int16 motor2_current
int16 motor2_speed
uint16 motor2_encoder
uint8 motor2_temperature

uint8 motor3_online
int16 motor3_current
int16 motor3_speed
uint16 motor3_encoder
uint8 motor3_temperature

uint8 motor4_online
int16 motor4_current
int16 motor4_speed
uint16 motor4_encoder
uint8 motor4_temperature
